flask_greenhouse/sensors/forms.py
#############################################################################################################################
#					IMPORTS																									#
#############################################################################################################################

from flask_wtf import FlaskForm

from wtforms.validators import DataRequired, ValidationError, EqualTo, Email, NumberRange
from wtforms_components import DateTimeField, DateRange
from wtforms_sqlalchemy.fields import QuerySelectField

from werkzeug.datastructures import MultiDict

from wtforms.fields import SubmitField, DateField, StringField, SelectField, IntegerField, PasswordField, BooleanField
from datetime import datetime
from wtforms.fields.html5 import DateTimeLocalField
from datetime import datetime
from flask_greenhouse.sensors.models import User, Sensor, SensorDataEntry

# login manager. It must be here to interact with things. 
from flask_login import login_required, login_user, current_user, logout_user
from flask_greenhouse import login_manager


#############################################################################################################################
#						LOGIN MANAGER DECORATORS																			#
#############################################################################################################################
@login_manager.user_loader
def load_user(user_id):
    return User.get(int(user_id))
	
#############################################################################################################################
#											FORMS																			#
#############################################################################################################################


#############################################################################################################################
#									USER REGISTRATION FORM																	#
#############################################################################################################################
class UserRegistrationForm(FlaskForm):
	username = StringField('Username', validators=[DataRequired()])
	email = StringField('Email', validators = [DataRequired(), Email()])
	password = PasswordField('Password', validators=[DataRequired()])
	confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
	submit = SubmitField('Sign Up')
	def validate_username(self, username):
		user = User.query.filter_by(username=username.data).first()
		if user:
			raise ValidationError('That username is taken. Please choose a different one.')
	def validate_email(self, email):
		user = User.query.filter_by(email=email.data).first()
		if user:
			raise ValidationError('That email is taken. Please choose a different one.')
			
#############################################################################################################################
#									USER LOGIN FORM																			#
#############################################################################################################################
class UserLoginForm(FlaskForm):
	username = StringField('Username', validators=[DataRequired()])
	password = PasswordField('Password', validators=[DataRequired()])
	remember = BooleanField('Remember Me')
	submit = SubmitField('Login')
	
#############################################################################################################################
#									SENSOR DATA REQUEST FORM																#
#############################################################################################################################
	
class SensorRequestForm(FlaskForm):
	sensors_owned = SelectField('Sensors owned', coerce=int, validators=[DataRequired()])
	start_date = DateTimeLocalField('Start Date', default=datetime.now())
	end_date = DateTimeLocalField('End Date', default=datetime.now())
	interval = IntegerField('Time Interval', default=10, validators=[DataRequired(), NumberRange(10,1000)])
	title = StringField('Title');
	x_axis = StringField('X axis')
	y_axis = StringField('Y axis')
	
	def validate_interval(form, interval):	# custom validators must be named "validate_<name of variable>".
		if (interval.data % 10): 
			raise ValidationError("Values must be a multiple of 10.")
			
	submit = SubmitField('Request Data') 

#############################################################################################################################
#									SENSOR REGISTRATION FORM																#
#############################################################################################################################	

class SensorRegistrationForm(FlaskForm):
	sensor_name = StringField('Enter The Name of the Sensor')
	units = StringField('Enter what units this sensor is measuring')
	protocol = StringField('Enter what protocol this sensor is using (optional at the moment)')
	type = StringField('Enter what your sensor is measuring')
	submit = SubmitField('Register your sensor')
	
	
#############################################################################################################################
#									SOURCES																					#
#############################################################################################################################

# https://stackoverflow.com/questions/46921823/dynamic-choices-wtforms-flask-selectfield
















#############################################################################################################################
#									TESTING AREA
#############################################################################################################################
class CityForm(FlaskForm):
	state = SelectField('state', choices=[('CA', 'California'), ('NV', 'Nevada')])
	city = SelectField('city', choices=[])

flask_greenhouse/bms/routes.py
#############################################################################################################################
#							IMPORTS																							#
#############################################################################################################################
from flask import render_template, request, Blueprint,flash, url_for, jsonify
from flask_greenhouse.forms import Date_Form
from flask_greenhouse.models import BMSDataentry
from flask_greenhouse.utils.plot import plot_graph, plot_date
from flask_greenhouse import db
import os
import json
from datetime import datetime, timedelta

# export this blueprint as "bms". Will be imported at __init__.py in the main folder.
bms = Blueprint("bms", __name__, static_folder='flask_greenhouse/static')

#############################################################################################################################
#							MAIN TRISTAR GRAPHING ROUTES																	#
#############################################################################################################################

@bms.route("/BMS", methods=["POST", "GET"])
def BMS_JS():
	form = Date_Form()
	return render_template("BMS.html", title="JS BMS data loader", form=form)

@bms.route("/BMS/serverside", methods=["POST", "GET"])
def BMS():
	form = Date_Form()
	if form.validate_on_submit():	
		#flash arguments; message, HTML class of message
		# flash this message when you submit this page.
		flash("Your request has been handled. Scroll down for your graph", 'success')
		
		# retrieve the start date and the end date from the form.
		# because it came from an HTML5 date form, it will automatically come in a datetime object.
		start_date = form.start_date.data
		end_date = form.end_date.data
		
		#request all data points from the BMS table that were posted after the start date, and before the end date.
		data_request = BMSDataentry.query.filter(BMSDataentry.date_posted < end_date).filter(BMSDataentry.date_posted > start_date)
		
		#filter the data request by making sure the dates are in intervals of the form interval. 
		#the form has a validator that says the integer must be a multiple of 10.
		
		interval = form.interval.data
		
		intervaled_data_request = [];
		# create a unit test.
		#if it's the battery charge:
		if form.y_axis.data == 'test':
				# fill in the x_data range with dummy values, starting from now to 40 minutes from now in steps of 10.
			# this guarantees 4 date points which the dummy y data will automatically correlate.
			x_data = [(datetime.now() + timedelta(minutes=step)) for step in range(0,40,10)]
			y_data = [4,6,8,10]
			x_label = "x-axis dummy data"
			y_label = "y-axis dummy data"
			title = "Hello world"
			style = form.style.data
			marker = form.marker.data
			tight_layout = True
			logarithmic_scale = False
			linestyle='solid'
			date_format = "%H:%M"
		else:
			#retrieve the data, and put it into x_data and y_data.
			x_data = []
			y_data = []
			for entry in data_request:
				x_data.append(entry.date_posted)
				y_data.append(entry.JSON_content["Battery Charge"]["battery charge"])
			x_label = form.xlabel.data
			y_label = form.ylabel.data
			title = form.title.data
			style = form.style.data
			marker = form.marker.data
			tight_layout = form.tight_layout.data
			logarithmic_scale = form.logarithmic_scale.data
			date_format = form.date_format.data
			linestyle='solid'
		
		#build the filepath.
		filepath = "flask_greenhouse/static/graphs/"#os.path.join(app.root_path, 'static/graphs/')	
		filename = "plot.png"
		
		# delete existing graph just in case. might change later this later and just rename it for every sensor.
		if os.path.exists(filepath+filename):
			os.remove(filepath+filename)
		
		#saves a graph to the filepath. (root/static/graphs/plot.png)
		plot_date(x_data, y_data, x_label, y_label, title, filepath, filename,
					style=style, marker=marker, logarithmic_scale=logarithmic_scale,
					tight_layout=tight_layout, linestyle=linestyle,
					date_format=date_format)
		
		return render_template('BMS_Server_side.html', form=form, graph=filename)
	return render_template('BMS_Server_side.html', form=form)

#########################################################################################################################
#							FILE VIEWING ROUTES																			#
#########################################################################################################################
@bms.route("/BMS/instantaneous", methods=["GET"])
@bms.route("/BMS/Instantaneous", methods=["GET"])
def BMS_Instantaneous():
	"""
		The Route to see Instantaneous BMS data.
		
		At the moment, it just loads a test file.
	"""
	filepath = "flask_greenhouse/BMS_test_file.json"
	with open(filepath, "r") as fp:	
		data = json.load(fp)
	return render_template("BMS_Instantaneous.html", data=data)

@bms.route("/BMS/pins", methods=["GET"])
def BMS_pins():
	"""
		The Route to see what Pins are currently attached.
		
		Reads from the current instantantous file.  
	"""
	filepath = "flask_greenhouse/BMS_test_file.json"
	with open(filepath, "r") as fp:	
		data = json.load(fp)
		pins = data["BMS Status"]["Pins Connected"]
	p = pins.split(',')
	return render_template("BMS_pins.html", pins=p)
#############################################################################################################################
#								POST ROUTES																					#
#############################################################################################################################
# post BMS JSON data to this address.
@bms.route("/BMS/post-json", methods=["POST"]) #get requests will be blocked.
def BMS_Post():
	"""
		The route for which BMS JSON data is posted. Will be sent by the Raspberry Pi we have on site.
	"""
	try:
		req_data = request.get_json() #extract JSON data from your request
		new_BMS_entry = BMSDataentry(JSON_content=req_data) # create new instance of 
		with open("flask_greenhouse/BMS_file.json", "w") as fp:
			json.dump(req_data, fp)
		db.session.add(new_BMS_entry)
		db.session.commit()
		return "your data has been received."
	except:
		return "error processing data", 500
	
#############################################################################################################################
#									APIs																					#
#								Getting BMS Data.																			#
#############################################################################################################################
@bms.route("/BMS/api/single_point/<string:date>/<string:parameter>", methods=["GET"])
def BMS_data_retrieval(date, parameter):
	"""
		Returns a single data point.
		
		Arguments:
			date: what date do you want to request?
			parameter: what parameter do you want?
		Returns:
			A JSON file. 
			Example:
			{
				"x": 1,
				"date": "2019-10-31 10:30:30",
				"parameter": "battery charge"
			}
		
	"""
	# parse the input datestring. strptime() should do the trick.
	datetime_from_JS = datetime.strptime(date, "%Y-%m-%d %H:%M:%S")
	# Search for BMS entries with a buffer of 30 seconds.
	entry = BMSDataentry.query \
			.filter( BMSDataentry.date_posted \
				.between(datetime_from_JS - timedelta(seconds=30), 
						 datetime_from_JS + timedelta(minutes=30)))\
				.first_or_404()
	# extract final entry date, JSON dictionary, and value. 
	final_entry_date = entry.date_posted
	dict = entry.JSON_content
	value = None
	try:
		value = dictionary_translation(dict, parameter)
	except:
		parameter = "error"
		value = None
	JSON_response = {
		
		"date": final_entry_date.strftime("%Y-%m-%d %H:%M:%S"),
		"parameter": parameter,
		"value": value
	}

	return jsonify(JSON_response)
	
@bms.route("/BMS/api/<string:start_date>/<string:end_date>/<int:interval>/<string:parameter>", methods=["GET"])
def BMS_multi_data_retrieval(start_date, end_date, interval, parameter):
	"""
		A server-side multi-data-point retrieval system.
		Arguments:
			start_date, end_date: from what date to what date do you want your points?
			interval (in minutes).
			parameter: what parameter do you want JSON data from?
		Returns:
			A JSON file.
			Example:
			{
				"parameter": "Battery Charge",
				"data": {
					"2019-10-31 10:30:44": 1,
					"2019-10-31 10:40:44": 2,
					"2019-10-31 10:50:44": 3,
					"2019-10-31 11:00:44": 4,
					"2019-10-31 11:10:44": 5,
					"2019-10-31 11:20:44": 5,
					"2019-10-31 11:30:44": 6
				}
			}
	"""
	# extrapolate dates from start, end, and interval.
	s = datetime.strptime(start_date, "%Y-%m-%d %H:%M:%S")
	e = datetime.strptime(end_date, "%Y-%m-%d %H:%M:%S")
	dates = []
	while(s < e):
		dates.append(s)
		s = s + timedelta(minutes=interval)
	
	# retrieve data from database based on date for all dates.
	data = {}
	for date in dates:
		value = None
		entry = BMSDataentry.query \
			.filter( BMSDataentry.date_posted \
				.between(date - timedelta(minutes=10), 
						 date + timedelta(minutes=10)))\
				.first()
		# once the entry is retrieved, (if there's an entry), extract the JSON content, 
		# try to find the parameter using dictionary translation, then if it's found, add it to the dataset.
		try:
			dict = entry.JSON_content
			value = dictionary_translation(dict, parameter)
			data[date.strftime("%Y-%m-%d %H:%M:%S")] = value
		except:
			pass
	# construct JSON response. 
	JSON_response = {
		"parameter": parameter,
		"data": data
	}
	return jsonify(JSON_response)
#############################################################################################################################
#					HELPER FUNCTIONS																						#
#############################################################################################################################

# dictionary_translation:
#	Arguments: 
# 		dict: a dictionary generated from a database retrieval.
#		parameter: the parameter you want.
# 	Returns:
# 		the value of the parameter wanted from the dictionary.
def dictionary_translation(dict, parameter):

flask_greenhouse/templates/BMS.html
{% extends "layout.html" %}

{% block content %}
	<h1>Request BMS Data</h1>
	<script>
	// logging the BMS URL here. 
	const BMS_URL = "{{ url_for('bms.BMS_data_retrieval', date='<date>', parameter='<parameter>') }}";
	console.log("URL TO MAKE REQUESTS TO \(UNFORMATTED\):" + BMS_URL);
	
	// make default dates to now.
	window.addEventListener("load", function() {
		var now = new Date();
		var utcString = now.toISOString().substring(0,19);
		var year = now.getFullYear();
		var month = now.getMonth() + 1;
		var day = now.getDate();
		var hour = now.getHours();
		var minute = now.getMinutes();
		var second = now.getSeconds();
		var localDatetime = year + "-" +
						  (month < 10 ? "0" + month.toString() : month) + "-" +
						  (day < 10 ? "0" + day.toString() : day) + "T" +
						  (hour < 10 ? "0" + hour.toString() : hour) + ":" +
						  (minute < 10 ? "0" + minute.toString() : minute);
						  //utcString.substring(16,19);
		var datetimeField = document.getElementById("start_date");
		datetimeField.value = localDatetime;
		var datetimeField2 = document.getElementById("end_date");
		datetimeField2.value = localDatetime;
	});
	</script>
{######################################################################################
							BMS Request Form.
							
			This form is controlled by BMS_graph_loader.js, located in the static folder.
			Please modify that JS file to modify the graphing mechanism.
			Pass in the single data point API URL by setting data-BASE_URL to it. 
			Pass in the multi data point API URL by setting data-MULTI_BASE_URL to it. 
			This only works in HTML5.
			
			Currently the API URLs are as follows:
			
			To retrieve a single datapoint, make a request to:
				http://<hostname>/BMS/api/single_data_point/<date>/<parameter>
			This will return a JSON file with this format:
				{
					"x": 1,
					"date": <date>,
					"parameter": <parameter>
				}
			Where x is the data point you seek.
			
			To retrieve multiple datapoints simultaneously, make a request to:
				http://<hostname>/BMS/api/<start_date>/<end_date>/<interval>/<parameter>
			This will return a JSON file with this format:
				"parameter": <parameter>,
				"data": {
					<start_date>: 1,
					<start_date> + <interval>: 2,
					<start_date> + 2*<interval>: 3 ,
						...
					<end_date>: n
				}
			Where the data points appear from start_date to end_date in intervals of <interval>.
##############################################################################################}
	<form action="#" id="BMS_form" data-BASE_URL="{{ url_for('bms.BMS_data_retrieval', date='<date>', parameter='<parameter>') }}", data-MULTI_BASE_URL="{{ url_for('bms.BMS_multi_data_retrieval', start_date='<start_date>', end_date='<end_date>', interval=5555, parameter='<parameter>') }}">
			<div class="row">
				<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
					{{ form.start_date.label }}
					{{ form.start_date }}
					<small class="form-text text-muted">Start date must be before 10/12/2019</small>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
					{{ form.end_date.label }}
					{{ form.end_date }}
					<small class="form-text text-muted">Start date must be before end date.</small>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
					{{ form.interval.label }}
					{{ form.interval }}
					<small class="form-text text-muted">Interval must be a multiple of 10 minutes.</small>
				</div>
			</div>
			<div class="form-group">
				{{ form.units.label }}
				{{ form.units }}
				
			</div>	
			<div class="form-group">
				<label for="title">Title</label><br />
				<input type="text" name="title" id="title" value="Untitled Graph">
			</div>
			<div class="row">
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
					<label for="xaxistitle">X-axis title</label><br />
					<input type="text" name="xaxistitle" id="xaxistitle">
				</div>
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
					<label for="yaxistitle">Y-axis title</label><br />
					<input type="text" name="yaxistitle" id="yaxistitle">
				</div>
			</div>
			<div class="row">
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 form-group">
					<label for="font_family">Font Family</label><br />
					<select name="font_family" id="style">
						<option value="Courier New">Courier New</option>
						<option value="Serif">Serif</option>
						<option value="Sans Serif">Sans Serif</option>
					</select>
				</div>
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 form-group">
					<label for="marker">Marker</label><br />
					<select name="marker" id="marker">
						<option value="fivethirtyeight">No Marker</option>
						<option value="classic">Star</option>
					</select>
				</div>
			</div>
			<div class="row">
				<div class="col">
					<label for="tightlayout">Tight Layout</label>
					<input type="checkbox" name="tightlayout" id="tightlayout">
				</div>
				<div class="col">
					<label for="logarithmic">Y-axis Logarithmic Scale</label>
					<input type="checkbox" name="logarithmic" id="logarithmic">
				</div>
			</div>
			
			<input type="submit" value="Request Graph">  
		</form>
		
	</form>
	<div id="chart"></div>
	<script src="{{ url_for('static', filename='BMS_graph_loader.js') }}"></script>
	
	<!-- we're keeping a local copy of plotly-latest for faster load speeds.-->
	<script src="{{ url_for('static', filename='plotly-latest.min.js') }}"> </script>
{######################################################################################
							Miscellaneous Links
		These are miscellaneous links that might be helpful.
		These links view the last data point sent to the server. 
		The last Tristar data point is written to an internal server folder as a file AND saved to our database.
		Opening a file in Python is faster than asking for it from the database, and easier to manage.
		
		Because the last data point lists the alarms, faults, and flags currently raised, it should be accessed very often.
					
######################################################################################}
	<p>
		<a href = "{{ url_for('bms.BMS_Instantaneous') }}">See instantaneous values</a><br />
		<a href = "{{ url_for('bms.BMS_pins') }}">See pins currently attached</a>
	</p>
{% endblock %}

flask_greenhouse/templates/BMS_Instantaneous.html
{% extends "layout.html" %}
{% import "macros.jinja" as macros %}
{% block content %}
<!-- https://getbootstrap.com/docs/4.3/content/tables/ -->
	<h1> BMS Values Now </h1>
	{% if data %}
		{{ macros.table_creator('Battery Balancing Rate Summary', data["Battery Balancing Rate Summary"] ) }}
		
		<h1>Battery Balancing Rate Detail</h1>
		{% for key, dict in data["Battery Balancing Rate Detail"].items() %}
			{{ macros.table_creator_with_units(key, dict) }}
		{% endfor %}
		
		{{ macros.table_creator_with_units('Battery Charge', data["Battery Charge"]) }}
		
		{{ macros.table_creator_with_units('Battery Module Temperature Summary', data["Battery Module Temperature Summary"]) }}
		
		<h1>Battery Module Temperature Detail</h1>
		{% for key, dict in data["Battery Module Temperature Detail"].items() %}
			{{ macros.table_creator_BMTD(key, dict) }}
		{% endfor %}
		
		{{ macros.table_creator_with_units("Battery Cell Temperature Summary", data["Battery Cell Temperature Summary"]) }}
		
		<h1>Battery Cell Temperature Detail</h1>
		{% set dd = data["Battery Cell Temperature Detail"].items() %}
		{% for key, dict in dd %}
			{{ macros.table_creator_BMTD(key, dict) }}
		{% endfor %}
		
		<h1>Battery Voltage Summary</h1>
		{{ macros.table_creator_with_units('Battery Voltage Summary', data['BatteryVoltageSummary']) }}
		
		<h1>Battery Voltage Detail</h1>
		{% set dd = data["BatteryVoltageDetail"].items() %}
		{% for key, dict in dd %}
			{{ macros.table_creator_BVD(key, dict) }}
		{% endfor %}
		<!-- receieved CAN bus Data -->
		{{ macros.table_creator('CAN Devices Status', data["CANDevicesStatus"]) }}
		{{ macros.table_creator("Received CAN Messages", data["ReceivedCANMessages"]) }}

		<!-- charger status -->
		{{ macros.table_creator_with_units("Charger Status", data["ChargerStatus"]) }}
		
		<!-- Current and voltage -->
		{{ macros.table_creator_with_units("Current and Voltage", data["CurrentAndVoltage"]) }}
		
		<!-- Input Pins -->
		{{ macros.table_creator_with_units("Input Pins", data["InputPins"]) }}
		
		<!-- Events Log -->
		{{ macros.table_creator_EVENT_LOG("Events Log", data["Events Log"]) }}
		
		<!-- Output Pins -->
		{{ macros.table_creator_with_units("Output Pins", data["OutputPins"]) }}
		
		<!--Statistics -->
		{{ macros.table_creator_EVENT_LOG("Statistics", data["Statistics"]) }}
		
		<!--BMS Status -->
		{{ macros.table_creator('BMS Status', data["BMS Status"]) }}
		
		<!-- Time and date according to the BMS unit -->
		<small class="text-muted">This is the Time and date according to the BMS internal clock at the moment. </small>
		{{ macros.table_creator('Time and Date', data["Time And Date"]) }}
			
			
		<!--"Version Number" -->
		{{ macros.table_creator('Version Data', data["Version Number"]) }}
	{% endif %}

	
	

{% endblock %}

flask_greenhouse/templates/BMS_Server_side.html
{% extends "layout.html" %}

{% block title %}This is an example page{% endblock %}

{% block scripts %}
  {{ super() }}
  {{ datepicker.loader() }}
  {{ datepicker.picker(id=".dp") }}

{% endblock %}

{% block content %}
		
	<form method="POST" action="">
		{{ form.hidden_tag() }} 
		<fieldset class="form-group"> 
			<legend class="border-bottom mb-4">Request BMS data</legend>
				<div class="form-group">
					{{ form.y_axis.label(class="form-control-label") }}
					
					{% if form.y_axis.errors %}
						{{ form.y_axis(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.y_axis.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.y_axis(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group"> 
					{{ form.start_date.label(class="form-control-label") }}
					
					{% if form.start_date.errors %}
						{{ form.start_date(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.start_date.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.start_date(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group"> 
					{{ form.end_date.label(class="form-control-label") }}
					
					{% if form.end_date.errors %}
						{{ form.end_date(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.end_date.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.end_date(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				Interval must be a multiple of 10 minutes.
				<div class="form-group"> 
					{{ form.interval.label(class="form-control-label") }}
					
					{% if form.interval.errors %}
						{{ form.interval(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.interval.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.interval(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.title.label(class="form-control-label") }}
					
					{% if form.title.errors %}
						{{ form.title(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.title.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.title(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.xlabel.label(class="form-control-label") }}
					
					{% if form.xlabel.errors %}
						{{ form.xlabel(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.xlabel.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.xlabel(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.ylabel.label(class="form-control-label") }}
					
					{% if form.ylabel.errors %}
						{{ form.ylabel(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.ylabel.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.ylabel(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.date_format.label(class="form-control-label") }} <a href="https://www.programiz.com/python-programming/datetime/strftime#format-code">Click here for a list of formats</a>
					
					{% if form.date_format.errors %}
						{{ form.date_format(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.date_format.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.date_format(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.style.label(class="form-control-label") }}
					
					{% if form.style.errors %}
						{{ form.style(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.style.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.style(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.tight_layout.label(class="form-control-label") }}
					
					{% if form.tight_layout.errors %}
						{{ form.tight_layout(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.tight_layout.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.tight_layout(class="form-control form-control-lg") }}
					{% endif %}
					
					{{ form.logarithmic_scale.label(class="form-control-label") }}
					
					{% if form.logarithmic_scale.errors %}
						{{ form.logarithmic_scale(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.logarithmic_scale.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.logarithmic_scale(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.marker.label(class="form-control-label") }}
					
					{% if form.marker.errors %}
						{{ form.marker(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.marker.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.marker(class="form-control form-control-lg") }}
					{% endif %}
				</div>
		</fieldset>
		<div class="form-group">
			{{ form.submit(class="btn btn-outline-info") }}
		</div>
		
	</form>
	<div id="display_data">
		{% if graph %}
			<img src = "{{ url_for('static', filename='graphs/' + graph) }} " />
		{% endif %}
	</div>
	<p>
		<a href = "{{ url_for('bms.BMS_Instantaneous') }}">See instantaneous values</a><br />
		<a href = "{{ url_for('bms.BMS_pins') }}">See pins currently attached</a>
	</p>
{% endblock %}

flask_greenhouse/templates/home.html
{% extends "layout.html" %}
{% block content %}
	<h1> Home </h1>
{% endblock %}